In [1]:
from pandas import read_csv
from pandas import set_option

In [16]:
filename = "data.csv".format(id, names=['user_id','order_number','order_dow','order_hour_of_day','days_since_prior_order','add_to_cart_order','reordered','product_id'])
data = read_csv(filename)

In [17]:
data.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,product_id
count,9.998700e+04,99987.000000,99987.000000,99987.000000,99987.000000,99987.000000,99987.000000,99987.000000,99987.000000
mean,1.686259e+06,935.043616,17.749137,2.758759,13.490584,10.174443,8.469481,0.584566,25583.960915
std,9.834043e+05,523.257459,18.321446,2.106281,4.186747,8.964301,7.336081,0.492799,14120.324467
min,2.140000e+02,3.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
25%,8.486470e+05,462.000000,5.000000,1.000000,10.000000,4.000000,3.000000,0.000000,13607.500000
50%,1.677961e+06,964.000000,11.000000,3.000000,13.000000,7.000000,6.000000,1.000000,25204.000000
75%,2.539865e+06,1411.000000,25.000000,5.000000,16.000000,14.000000,12.000000,1.000000,37973.000000
max,3.420235e+06,1819.000000,99.000000,6.000000,23.000000,30.000000,62.000000,1.000000,49683.000000